/**
 * \file event.h
 * \brief Contains code related to events.
 */
#pragma once

/**
 * \enum HxfEventType
 * \brief The type of an HxfEvent
 */
typedef enum HxfEventType {
    HXF_EVENT_TYPE_KEYPRESS, ///< The key is pressed
    HXF_EVENT_TYPE_KEYRELEASE ///< The key is released
} HxfEventType;

/**
 * \enum HxfEventKey
 * \brief Represents a key.
 */
typedef enum HxfEventKey {
    HXF_EVENT_KEY_UNKNOWN, ///< Unknown key
    HXF_EVENT_KEY_ESCAPE, ///< The escape key
    HXF_EVENT_KEY_SPACE ///< The spacebar key
} HxfEventKey;

/**
 * \struct HxfEvent
 * \brief An event generated by a HxfWindow.
 */
typedef struct HxfEvent {
    HxfEventType type; ///< The type of the event
    HxfEventKey key; ///< The key related to the event
} HxfEvent;